# Generated by Django 4.2.8 on 2024-01-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sha2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichier',
            name='path',
            field=models.FileField(upload_to='fichiers'),
        ),
    ]
