# Generated by Django 4.2.8 on 2024-03-27 22:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Sha2', '0003_fichier_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
